name: Watt
options:
  bundleIdPrefix: com.watt
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: Watt
    MARKETING_VERSION: 1.5.3
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES

targets:
  Watt:
    type: application
    platform: macOS
    sources:
      - path: Watt/Sources
        type: group
      - path: Watt/Resources
        type: group
    postCompileScripts:
      - name: Set Build Number
        script: |
          # Get git commit count as build number
          BUILD_NUMBER=$(git rev-list --count HEAD 2>/dev/null || echo "1")
          # Get git short hash
          GIT_HASH=$(git rev-parse --short=5 HEAD 2>/dev/null || echo "00000")

          # Update Info.plist with build number
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $BUILD_NUMBER" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" 2>/dev/null || \
          /usr/libexec/PlistBuddy -c "Add :CFBundleVersion string $BUILD_NUMBER" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" 2>/dev/null || true

          # Write git hash to a file that can be read at runtime
          echo "$GIT_HASH" > "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/GitHash.txt"
        basedOnDependencyAnalysis: false
    settings:
      base:
        INFOPLIST_FILE: Watt/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.watt.app
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/../Frameworks
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: YES
        ENABLE_PREVIEWS: YES
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
    info:
      path: Watt/Resources/Info.plist
      properties:
        CFBundleName: Watt
        CFBundleDisplayName: Watt
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundlePackageType: APPL
        CFBundleExecutable: $(EXECUTABLE_NAME)
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2026 Zimeng Xiong. All rights reserved."
        NSPrincipalClass: NSApplication
    entitlements:
      path: Watt/Resources/Watt.entitlements
      properties:
        com.apple.security.app-sandbox: false
